// This file is @generated by prost-build.
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct MovieParams {
    #[prost(float, tag = "1")]
    pub view_box_width: f32,
    #[prost(float, tag = "2")]
    pub view_box_height: f32,
    #[prost(int32, tag = "3")]
    pub fps: i32,
    #[prost(int32, tag = "4")]
    pub frames: i32,
}
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct Layout {
    #[prost(float, tag = "1")]
    pub x: f32,
    #[prost(float, tag = "2")]
    pub y: f32,
    #[prost(float, tag = "3")]
    pub width: f32,
    #[prost(float, tag = "4")]
    pub height: f32,
}
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct Transform {
    #[prost(float, tag = "1")]
    pub a: f32,
    #[prost(float, tag = "2")]
    pub b: f32,
    #[prost(float, tag = "3")]
    pub c: f32,
    #[prost(float, tag = "4")]
    pub d: f32,
    #[prost(float, tag = "5")]
    pub tx: f32,
    #[prost(float, tag = "6")]
    pub ty: f32,
}
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct RgbaColor {
    #[prost(float, tag = "1")]
    pub r: f32,
    #[prost(float, tag = "2")]
    pub g: f32,
    #[prost(float, tag = "3")]
    pub b: f32,
    #[prost(float, tag = "4")]
    pub a: f32,
}
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct ShapeStyle {
    #[prost(message, optional, tag = "1")]
    pub fill: ::core::option::Option<RgbaColor>,
    #[prost(message, optional, tag = "2")]
    pub stroke: ::core::option::Option<RgbaColor>,
    #[prost(float, tag = "3")]
    pub stroke_width: f32,
    #[prost(enumeration = "LineCap", tag = "4")]
    pub line_cap: i32,
    #[prost(enumeration = "LineJoin", tag = "5")]
    pub line_join: i32,
    #[prost(float, tag = "6")]
    pub miter_limit: f32,
    #[prost(float, tag = "7")]
    pub line_dash_i: f32,
    #[prost(float, tag = "8")]
    pub line_dash_ii: f32,
    #[prost(float, tag = "9")]
    pub line_dash_iii: f32,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ShapeArgs {
    #[prost(string, tag = "1")]
    pub d: ::prost::alloc::string::String,
}
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct RectArgs {
    #[prost(float, tag = "1")]
    pub x: f32,
    #[prost(float, tag = "2")]
    pub y: f32,
    #[prost(float, tag = "3")]
    pub width: f32,
    #[prost(float, tag = "4")]
    pub height: f32,
    #[prost(float, tag = "5")]
    pub corner_radius: f32,
}
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct EllipseArgs {
    #[prost(float, tag = "1")]
    pub x: f32,
    #[prost(float, tag = "2")]
    pub y: f32,
    #[prost(float, tag = "3")]
    pub radius_x: f32,
    #[prost(float, tag = "4")]
    pub radius_y: f32,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ShapeEntity {
    #[prost(enumeration = "ShapeType", tag = "1")]
    pub r#type: i32,
    #[prost(message, optional, tag = "10")]
    pub styles: ::core::option::Option<ShapeStyle>,
    #[prost(message, optional, tag = "11")]
    pub transform: ::core::option::Option<Transform>,
    #[prost(oneof = "shape_entity::Args", tags = "2, 3, 4")]
    pub args: ::core::option::Option<shape_entity::Args>,
}
/// Nested message and enum types in `ShapeEntity`.
pub mod shape_entity {
    #[derive(Clone, PartialEq, ::prost::Oneof)]
    pub enum Args {
        #[prost(message, tag = "2")]
        Shape(super::ShapeArgs),
        #[prost(message, tag = "3")]
        Rect(super::RectArgs),
        #[prost(message, tag = "4")]
        Ellipse(super::EllipseArgs),
    }
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct FrameEntity {
    #[prost(float, tag = "1")]
    pub alpha: f32,
    #[prost(message, optional, tag = "2")]
    pub layout: ::core::option::Option<Layout>,
    #[prost(message, optional, tag = "3")]
    pub transform: ::core::option::Option<Transform>,
    #[prost(string, tag = "4")]
    pub clip_path: ::prost::alloc::string::String,
    #[prost(message, repeated, tag = "5")]
    pub shapes: ::prost::alloc::vec::Vec<ShapeEntity>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct SpriteEntity {
    #[prost(string, tag = "1")]
    pub image_key: ::prost::alloc::string::String,
    #[prost(message, repeated, tag = "2")]
    pub frames: ::prost::alloc::vec::Vec<FrameEntity>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct MovieEntity {
    #[prost(string, tag = "1")]
    pub version: ::prost::alloc::string::String,
    #[prost(message, optional, tag = "2")]
    pub params: ::core::option::Option<MovieParams>,
    #[prost(map = "string, bytes", tag = "3")]
    pub images: ::std::collections::HashMap<
        ::prost::alloc::string::String,
        ::prost::alloc::vec::Vec<u8>,
    >,
    #[prost(message, repeated, tag = "4")]
    pub sprites: ::prost::alloc::vec::Vec<SpriteEntity>,
}
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum LineCap {
    Butt = 0,
    Round = 1,
    Square = 2,
}
impl LineCap {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Self::Butt => "LineCap_BUTT",
            Self::Round => "LineCap_ROUND",
            Self::Square => "LineCap_SQUARE",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "LineCap_BUTT" => Some(Self::Butt),
            "LineCap_ROUND" => Some(Self::Round),
            "LineCap_SQUARE" => Some(Self::Square),
            _ => None,
        }
    }
}
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum LineJoin {
    Miter = 0,
    Round = 1,
    Bevel = 2,
}
impl LineJoin {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Self::Miter => "LineJoin_MITER",
            Self::Round => "LineJoin_ROUND",
            Self::Bevel => "LineJoin_BEVEL",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "LineJoin_MITER" => Some(Self::Miter),
            "LineJoin_ROUND" => Some(Self::Round),
            "LineJoin_BEVEL" => Some(Self::Bevel),
            _ => None,
        }
    }
}
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum ShapeType {
    Shape = 0,
    Rect = 1,
    Ellipse = 2,
    Keep = 3,
}
impl ShapeType {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Self::Shape => "SHAPE",
            Self::Rect => "RECT",
            Self::Ellipse => "ELLIPSE",
            Self::Keep => "KEEP",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "SHAPE" => Some(Self::Shape),
            "RECT" => Some(Self::Rect),
            "ELLIPSE" => Some(Self::Ellipse),
            "KEEP" => Some(Self::Keep),
            _ => None,
        }
    }
}
